PatientManagementSoftware/Controllers/PRACTICE_APPOINTMENTController.cs
using PatientManagementSoftware.DAL;
using PatientManagementSoftware.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PatientManagementSoftware.Controllers
{
    public class PRACTICE_APPOINTMENTController : Controller
    {
        // GET: PRACTICE_APPOINTMENT

        DataAccessLayer Layer;
        public ActionResult Index()
        {
            Layer = new DataAccessLayer();

            string Query = "ManageAppointmentsDML";

            List<AppointmentViewModel> appointmentList = new List<AppointmentViewModel>();

            SqlParameter[] sqlParameter = new SqlParameter[]
            {
             new SqlParameter("@Action","select"),   

            };

            DataTable dataTable= Layer.ExecuteStoredProcedure(Query, sqlParameter);

            foreach(DataRow item in dataTable.Rows)
            {
                AppointmentViewModel appointmentViewModel = new AppointmentViewModel
                {
                    Id= Convert.ToInt32(item["AppointmentID"]),
                    PatientName= item["PatientName"].ToString(),
                    DoctorName= item["DoctorName"].ToString(),
                    AppointmentDateTime = Convert.ToDateTime(item["AppointmentDateTime"]),
                    Reason = item["Reason"].ToString(),
                    Status = item["status"].ToString()
                };

                appointmentList.Add(appointmentViewModel);
            }
            return  View(appointmentList);
        }

        public ActionResult SaveAppointment()
        {      
            ViewBag.PatientList=GetPatients();

            ViewBag.Doctorlist=GetDoctors();

            return View();

        }



        public ActionResult BookAppointment(AppointmentViewModel model)
        {
            Layer = new DataAccessLayer();

            string q = "ManageAppointmentsDML";

            SqlParameter[] parameters = new SqlParameter[]
            {
                new SqlParameter("@Action","Insert"),
                new SqlParameter("@PatientID",model.PatientID),
                new SqlParameter("@doctorID",model.DoctorID),
                new SqlParameter("@AppointmentDateTime",model.AppointmentDateTime),
                new SqlParameter("@Reason",model.Reason),
                new SqlParameter("@Status",model.Status),
            };

            Layer.ExecuteStoredProcedure(q,parameters);

            return RedirectToAction("Index");   
        }

        public ActionResult Edit(int Id)
        {
            Layer= new DataAccessLayer();

            string q = "GetDataByID";

            SqlParameter[] sqlParameter = new SqlParameter[]
            {
                 new SqlParameter("@ChooseTable","Appointment"),
                new SqlParameter("@AppointmentID",Id),  
            };

            AppointmentViewModel model = new AppointmentViewModel();


            ViewBag.PatientList = GetPatients();

            ViewBag.DoctorList=GetDoctors();

            DataTable dt = Layer.ExecuteStoredProcedure(q,sqlParameter);

            foreach (DataRow dr in dt.Rows)
            {
                model.Id = Convert.ToInt32(dr["AppointmentID"]);
                model.PatientID = Convert.ToInt32(dr["PatientID"]);
                model.DoctorID = Convert.ToInt32(dr["DoctorID"]);
                model.AppointmentDateTime = Convert.ToDateTime(dr["AppointmentDateTime"]);
                model.Reason = dr["Reason"].ToString();
                model.Status = dr["status"].ToString(); 
            }
                return View(model);
        }


        public ActionResult UpdateAppointment(AppointmentViewModel model)
        {

            Layer= new DataAccessLayer();

            string PROC_NAME = "ManageAppointmentsDML";

            SqlParameter[] sqlParameter = new SqlParameter[]
            {
                new SqlParameter("@Action","Update"),
                new SqlParameter("@AppointmentID",model.Id),
                new SqlParameter("@PatientID",model.PatientID),
                new SqlParameter("@DoctorID",model.DoctorID),
                new SqlParameter("@AppointmentDateTime",model.AppointmentDateTime),
                new SqlParameter("@Reason",model.Reason),
                new SqlParameter("@Status",model.Status),
            };

            Layer.ExecuteStoredProcedure(PROC_NAME, sqlParameter);
            return RedirectToAction("Index");
        }







        // DELETE METHOD
        public ActionResult Delete( int id)
        {
            Layer= new DataAccessLayer();

            string query = "ManageAppointmentsDML";

            SqlParameter[] parameters = new SqlParameter[]
            {
                new SqlParameter("@Action","Delete"),
                new SqlParameter("@AppointmentID",id),
            };
            
            Layer.ExecuteStoredProcedure(query, parameters);

            return RedirectToAction("Index");
        }

        public List<PatientViewModel> GetPatients()
        {
            Layer= new DataAccessLayer();

            List<PatientViewModel> patients= new List<PatientViewModel>();

            string Query = "ManagePatientsDML";

            SqlParameter[] sqlParameters = new SqlParameter[]
            {
                new SqlParameter("@Action","Select"),
            };

            DataTable dataTable = Layer.ExecuteStoredProcedure(Query,sqlParameters);

            foreach (DataRow row in dataTable.Rows)
            {
                patients.Add(new PatientViewModel()
                {
                    PatientID = Convert.ToInt32(row["PatientID"]),
                    Name = Convert.ToString(row["Name"]),
                });
            }
          
            return patients;
        }



        public List<DoctorViewModel>GetDoctors()
        {
            Layer= new DataAccessLayer();

            List<DoctorViewModel> doctorlist = new List<DoctorViewModel>();

            string query = "ManageDoctorsDML";

            SqlParameter[] sqlParameters = new SqlParameter[]
            {
                new SqlParameter("@Action","Select"),
            };

            DataTable dt= Layer.ExecuteStoredProcedure(query,sqlParameters);

            foreach (DataRow row in dt.Rows)
            {
                doctorlist.Add(new DoctorViewModel()
                {
                    DoctorID = Convert.ToInt32(row["DoctorID"]),
                    Name = Convert.ToString(row["Name"]),
                });
            }
            return doctorlist;
        }        
    }  
}

PatientManagementSoftware/Views/PRACTICE_APPOINTMENT/Edit.cshtml
@model PatientManagementSoftware.Models.AppointmentViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
@using (Html.BeginForm("UpdateAppointment", "PRACTICE_APPOINTMENT", FormMethod.Post, new { @class = "form-signin" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model=>model.Id)

    <div class="form-group mb-2">
        @Html.LabelFor(model => model.PatientID, new { @class = "sr-only" })
        @Html.DropDownListFor(model => model.PatientID, new SelectList(ViewBag.PatientList, "PatientID", "Name"), "--Select Patient--", new { @class = "form-control", type = "text" })
    </div>

    <div class="form-group mb-2">
        @Html.LabelFor(model => model.DoctorID, new { @class = "sr-only" })
        @Html.DropDownListFor(model => model.DoctorID, new SelectList(ViewBag.DoctorList, "DoctorId", "Name"), "--Select Doctor", new { @class = "form-control", type = "text" })
    </div>

    <div class="form-group mb-2">
        @Html.LabelFor(model => model.AppointmentDateTime, new { @class = "sr-only" })
        @Html.TextBoxFor(model => model.AppointmentDateTime, new { @class = "form-control", placeholder = "Appointment Date Time", type = "datetime-local", required = "required" })
    </div>

    <div class="form-group mb-2">
        @Html.LabelFor(model => model.Reason, new { @class = "sr-only" })
        @Html.TextBoxFor(model => model.Reason, new { @class = "form-control", placeholder = "Reason", required = "required" })
    </div>

    <div class="form-group mb-2">
        @Html.LabelFor(model => model.Status, new { @class = "sr-only" })
        @Html.TextBoxFor(model => model.Status, new { @class = "form-control", placeholder = "Status", required = "required" })
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.SelectedType, new { @class = "sr-only" })
            @Html.DropDownListFor(model => model.SelectedType, new SelectList(Model.Types ?? new List<string>()), new { @class = "form-control", required = "required" })
        </div>*@
    <button class="btn btn-lg btn-primary btn-block mb-2" type="submit">Submit</button>

}

PatientManagementSoftware/Views/PRACTICE_APPOINTMENT/Index.cshtml
@model List<PatientManagementSoftware.Models.AppointmentViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<div class="row" style="margin-bottom:10px;">

    <div class="col-2">
        <a href="@Url.Action("SaveAppointment", "PRACTICE_APPOINTMENT")" class="btn btn-primary">Register Appointment</a>
    </div>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>AppoinmetID</th>
            <th>Patient Name</th>
            <th>Doctor Name</th>
            <th>Appointment Date</th>
            <th>Reason</th>
            <th>Status </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
       @foreach (var appointment in Model)
       {
                <tr>
                    <td>@appointment.Id</td>
                    <td>@appointment.PatientName</td>
                    <td>@appointment.DoctorName</td>
                    <td>@appointment.AppointmentDateTime</td>
                    <td>@appointment.Reason</td>
                    <td>@appointment.Status</td>
                    <td>
                        <a href="@Url.Action("Edit", "PRACTICE_APPOINTMENT", new { Id = appointment.Id })" class="btn btn-primary">Edit</a>
                        <a href="@Url.Action("Delete", "PRACTICE_APPOINTMENT", new { Id = appointment.Id})" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
    </tbody>
    </table>

PatientManagementSoftware/Views/PRACTICE_APPOINTMENT/SaveAppointment.cshtml
@model PatientManagementSoftware.Models.AppointmentViewModel
@{
    ViewBag.Title = "SaveAppointment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SaveAppointment</h2>

@using (Html.BeginForm("BookAppointment", "PRACTICE_APPOINTMENT", FormMethod.Post, new { @class = "form-signin" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group mb-2">
        @Html.LabelFor(model => model.PatientID, new { @class = "sr-only" })
        @Html.DropDownListFor(model => model.PatientID, new SelectList(ViewBag.PatientList, "PatientID", "Name"), "--Select Patient--", new { @class = "form-control", type = "text" })
    </div>

    <div class="form-group mb-2">
       @Html.LabelFor(model=>model.DoctorID,  new{ @class="sr-only"})
        @Html.DropDownListFor(model=>model.DoctorID,new SelectList(ViewBag.DoctorList,"DoctorId","Name"),"--Select Doctor",new{@class="form-control",type="text" })
    </div>

    <div class="form-group mb-2">
        @Html.LabelFor(model => model.AppointmentDateTime, new { @class = "sr-only" })
        @Html.TextBoxFor(model => model.AppointmentDateTime, new { @class = "form-control", placeholder = "Appointment Date Time", type = "datetime-local", required = "required" })
    </div>

    <div class="form-group mb-2">
        @Html.LabelFor(model => model.Reason, new { @class = "sr-only" })
        @Html.TextBoxFor(model => model.Reason, new { @class = "form-control", placeholder = "Reason", required = "required" })
    </div>

    <div class="form-group mb-2">
        @Html.LabelFor(model => model.Status, new { @class = "sr-only" })
        @Html.TextBoxFor(model => model.Status, new { @class = "form-control", placeholder = "Status", required = "required" })
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.SelectedType, new { @class = "sr-only" })
            @Html.DropDownListFor(model => model.SelectedType, new SelectList(Model.Types ?? new List<string>()), new { @class = "form-control", required = "required" })
        </div>*@
    <button class="btn btn-lg btn-primary btn-block mb-2" type="submit">Submit</button>

}