PatientManagementSoftware/Controllers/DashboardController.cs
using PatientManagementSoftware.DAL;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PatientManagementSoftware.Controllers
{

    [Authorize]
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {

            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                int totalPatients, totalDoctors, totalAppointments, totalMedicalRecords;
                decimal totalBilling;
                DataAccessLayer dal = new DataAccessLayer();
                // Call the stored procedure and get output values
                string query = "GetDashboardData";
                SqlParameter[] parameters = new SqlParameter[]
                {
                 new SqlParameter("@totalPatients", SqlDbType.Int) { Direction = ParameterDirection.Output },
                 new SqlParameter("@totalDoctors", SqlDbType.Int) { Direction = ParameterDirection.Output },
                 new SqlParameter("@totalAppointments", SqlDbType.Int) { Direction = ParameterDirection.Output },
                 new SqlParameter("@totalMedicalRecords", SqlDbType.Int) { Direction = ParameterDirection.Output },
                 new SqlParameter("@totalBilling", SqlDbType.Money) { Direction = ParameterDirection.Output }

                };

                DataTable result = dal.ExecuteStoredProcedure(query, parameters);

                // Populate ViewBag with retrieved data
                // Retrieve output values
                totalPatients = Convert.ToInt32(parameters[0].Value);
                totalDoctors = Convert.ToInt32(parameters[1].Value);
                totalAppointments = Convert.ToInt32(parameters[2].Value);
                totalMedicalRecords = Convert.ToInt32(parameters[3].Value);
                totalBilling = Convert.ToDecimal(parameters[4].Value);

                // Pass the retrieved data to the view
                ViewBag.TotalPatients = totalPatients;
                ViewBag.TotalDoctors = totalDoctors;
                ViewBag.TotalAppointments = totalAppointments;
                ViewBag.TotalMedicalRecords = totalMedicalRecords;
                ViewBag.TotalBilling = totalBilling.ToString("0.00");


                return View();
            }
        }
    }
}

PatientManagementSoftware/Controllers/InvoicingController.cs
using PatientManagementSoftware.DAL;
using PatientManagementSoftware.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PatientManagementSoftware.Controllers
{
    [Authorize]
    public class InvoicingController : Controller
    {
        // GET: Invoicing

        DataAccessLayer dal;

        public List<PatientViewModel> PatientDDL() //This is a function which retunr list of type PatientViewModel
        {

            // PatientDDL Patient Drop down list
            List<PatientViewModel> patientList = new List<PatientViewModel>();

            DataAccessLayer dataAccessLayer = new DataAccessLayer();

            SqlParameter[] parameters = new SqlParameter[]
            {
             new SqlParameter("@Action", "select")
            };

            DataTable patientdt = dataAccessLayer.ExecuteStoredProcedure("ManagePatientsDML", parameters);

            foreach (DataRow dr in patientdt.Rows)
            {
                patientList.Add(new PatientViewModel
                {
                    PatientID = Convert.ToInt32(dr["PatientID"]),
                    Name = dr["Name"].ToString(),
                });
            }
            return patientList;
        }

        public ActionResult Index()
        {
            dal = new DataAccessLayer();

            //Geting Dropdownlist Data

            ViewBag.PatientList = PatientDDL();

            string query = "ManageInvoiceDML";

            SqlParameter[] parameters = new SqlParameter[]
            {
             new SqlParameter("@Action", "select")
            };

            DataTable dt = dal.ExecuteStoredProcedure(query, parameters);

            List<BillingViewModel> BillingList = new List<BillingViewModel>();

            foreach (DataRow dr in dt.Rows)
            {
                BillingViewModel model = new BillingViewModel()
                {
                    BillID = Convert.ToInt32(dr["BillID"]),
                    PatientID = Convert.ToInt32(dr["PatientID"]),
                    PatientName = dr["PatientName"].ToString(),
                    BillDate = Convert.ToDateTime(dr["BillDate"]),
                    Amount = Convert.ToDecimal(dr["Amount"].ToString()),
                    PaymentStatus = dr["PaymentStatus"].ToString()
                };
                BillingList.Add(model);
            }
            ViewBag.list = BillingList;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateInvoice(BillingViewModel model)
        {
            if (ModelState.IsValid)
            {
                dal = new DataAccessLayer();

                ViewBag.PatientList = PatientDDL();

                string query = "ManageInvoiceDML";

                SqlParameter[] parameters = new SqlParameter[]
                {
                    new SqlParameter("@Action","insert"),
                    new SqlParameter("@PatientID",model.PatientID),
                    new SqlParameter("@BillDate",model.BillDate),
                    new SqlParameter("@Amount",model.Amount),
                    new SqlParameter("@PaymentStatus",model.PaymentStatus)
                };

                DataTable dt = dal.ExecuteStoredProcedure(query, parameters);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Invoice()
        {
            ViewBag.PatientList = PatientDDL();


            return View();
        }

        /*public ActionResult CreateInvoice()
        {
            return View();
        }*/
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ///

        public ActionResult PrintInvoice(int billId)
        {
            dal = new DataAccessLayer();

            BillingViewModel model = new BillingViewModel();

            SqlParameter[] parameters = new SqlParameter[]
            {
                new SqlParameter("@BillID", billId)
            };

            DataTable patientdt = dal.ExecuteStoredProcedure("GetInvoiceByPatient", parameters);

            foreach (DataRow dr in patientdt.Rows)
            {
                model.BillID = Convert.ToInt32(dr["BillID"]);
                model.BillDate = Convert.ToDateTime(dr["BillDate"].ToString());
                model.Amount = Convert.ToDecimal(dr["Amount"].ToString());
                model.PatientID = Convert.ToInt32(dr["PatientID"].ToString());
                model.PatientName = dr["PatientName"].ToString();
                model.PaymentStatus = dr["PaymentStatus"].ToString();
            };
            return View(model);

        }

        public ActionResult Edit(int id)
        {
            BillingViewModel model = new BillingViewModel();

            string query = "GetDataByID";

            DataAccessLayer dataAccessLayer = new DataAccessLayer();

            ViewBag.PatientList1 = PatientDDL();

            SqlParameter[] sqlParameter = new SqlParameter[]
            {
                new SqlParameter("@ChooseTable","Billing"),
                new SqlParameter("@BillID",id)
            };

            DataTable result = dataAccessLayer.ExecuteStoredProcedure(query, sqlParameter);

            foreach (DataRow dr in result.Rows)
            {
                model.BillID = Convert.ToInt32(dr["BillID"]);
                model.PatientID = Convert.ToInt32(dr["PatientID"]);
                model.BillDate = Convert.ToDateTime(dr["BillDate"]);
                model.Amount = Convert.ToDecimal(dr["Amount"]);
                model.PaymentStatus = dr["PaymentStatus"].ToString();
            }
            return View(model);
        }


        [HttpPost]
        public ActionResult Update(BillingViewModel model)
        {
            if (ModelState.IsValid)
            {
                dal = new DataAccessLayer();

                ViewBag.PatientList1 = PatientDDL();

                string query = "ManageInvoiceDML";

                SqlParameter[] parameters = new SqlParameter[]
                {
                    new SqlParameter("@Action","update"),
                    new SqlParameter("BillID",model.BillID),
                    new SqlParameter("@PatientID",model.PatientID),
                    new SqlParameter("@BillDate",model.BillDate),
                    new SqlParameter("@Amount",model.Amount),
                    new SqlParameter("@PaymentStatus",model.PaymentStatus)
                };

                DataTable dt = dal.ExecuteStoredProcedure(query, parameters);
                return RedirectToAction("Index");
            }
            return View();
        }
        

        public ActionResult Delete(int id)
        {
            dal = new DataAccessLayer();

            string query = "[ManageInvoiceDML]";

            SqlParameter[] sqlParameters = new SqlParameter[]
            {
                new SqlParameter("@Action","delete"),
                new SqlParameter("@BillID",id), 
            };

            DataTable result= dal.ExecuteStoredProcedure(query, sqlParameters);

            return RedirectToAction("Index");
        }

        public ActionResult print()
        {
            return View();
        }
    }


    
}

PatientManagementSoftware/Controllers/MedicalRecordsController.cs
using PatientManagementSoftware.DAL;
using PatientManagementSoftware.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PatientManagementSoftware.Controllers
{
    [Authorize]
    public class MedicalRecordsController : Controller
    {
        // GET: MedicalRecords

        DataAccessLayer dataAccessLayer;
        public ActionResult Index()
        {
            DataAccessLayer dataAccessLayer = new DataAccessLayer();

            List<MedicalRecordViewModel> records = new List<MedicalRecordViewModel>();

            SqlParameter[] sqlParameter = new SqlParameter[]
            {
                new SqlParameter("@Action","Select"),
            };

            DataTable dataTable = dataAccessLayer.ExecuteStoredProcedure("SPMedicalRecordsDML", sqlParameter);

            foreach (DataRow data in dataTable.Rows)
            {
                MedicalRecordViewModel recordViewModel = new MedicalRecordViewModel
                {

                    RecordID = Convert.ToInt32(data["RecordID"]),
                    PatientName = data["PatientName"].ToString(),
                    DoctorName = data["DoctorName"].ToString(),
                    Diagnosis = data["Diagnosis"].ToString(),
                    Treatment = data["Treatment"].ToString(),
                    Medications = data["Medications"].ToString(),
                    BloodGroup = data["BloodGroup"].ToString(),

                };
                records.Add(recordViewModel);
            }
            return View(records);

        }

        public List<DoctorViewModel> DoctorDDL()
        {
            List<DoctorViewModel> doctorList = new List<DoctorViewModel>();

            DataAccessLayer dataAccessLayer = new DataAccessLayer();

            SqlParameter[] parameters = new SqlParameter[]
            {
             new SqlParameter("@Action", "select")
            };

            DataTable doctordt = dataAccessLayer.ExecuteStoredProcedure("ManageDoctorsDML", parameters);

            foreach (DataRow dr in doctordt.Rows)
            {
                doctorList.Add(new DoctorViewModel
                {
                    DoctorID = Convert.ToInt32(dr["DoctorID"]),
                    Name = dr["Name"].ToString(),
                });
            }
            return doctorList;
        }


        public List<PatientViewModel> PatientDDL()
        {
            List<PatientViewModel> patientList = new List<PatientViewModel>();

            DataAccessLayer dataAccessLayer = new DataAccessLayer();

            SqlParameter[] parameters = new SqlParameter[]
            {
             new SqlParameter("@Action", "select")
            };

            DataTable patientdt = dataAccessLayer.ExecuteStoredProcedure("ManagePatientsDML", parameters);

            foreach (DataRow dr in patientdt.Rows)
            {
                patientList.Add(new PatientViewModel
                {
                    PatientID = Convert.ToInt32(dr["PatientID"]),
                    Name = dr["Name"].ToString(),
                });
            }
            return patientList;
        }

        public ActionResult SaveMedicalRecord(MedicalRecordViewModel model)
        {
            string Query = "SPMedicalRecordsDML";

            if (ModelState.IsValid)
            {
                dataAccessLayer = new DataAccessLayer();

                SqlParameter[] sqlParameters = new SqlParameter[]
                {
                 new SqlParameter("@Action","Insert"),
                 new SqlParameter("@PatientID",model.PatientID),
                 new SqlParameter("@DoctorID",model.DoctorID),
                 new SqlParameter("@Diagnosis",model.Diagnosis),
                 new SqlParameter("@Treatment",model.Treatment),
                 new SqlParameter("@Medications",model.Medications),
                 new SqlParameter("@BloodGroup",model.BloodGroup),
                };

                DataTable result = dataAccessLayer.ExecuteStoredProcedure(Query, sqlParameters);

                return RedirectToAction("Index");


            }

            return View(model);

        }

        public ActionResult AddMedicalRecord(MedicalRecordViewModel model)
        {
            ViewBag.PatientList = PatientDDL();

            ViewBag.DoctorList = DoctorDDL();
            return View(model);
        }

        public ActionResult Edit(int ID)
        {
            dataAccessLayer = new DataAccessLayer();

            ViewBag.PatientList = PatientDDL();

            ViewBag.DoctorList = DoctorDDL();

            string Query = "GetDataByID";

            MedicalRecordViewModel model = new MedicalRecordViewModel();

            SqlParameter[] parameters = new SqlParameter[]
            {
                new SqlParameter("@ChooseTable", "MedicalRecord "),
                new SqlParameter("@RecordID", ID)
            };

            DataTable patientdt = dataAccessLayer.ExecuteStoredProcedure(Query, parameters);

            foreach (DataRow dr in patientdt.Rows)
            {
                model.RecordID = Convert.ToInt32(dr["RecordID"]);
                model.PatientID = Convert.ToInt32(dr["PatientID"]);
                model.DoctorID = Convert.ToInt32(dr["DoctorID"]);
                model.Diagnosis = dr["Diagnosis"].ToString();
                model.Treatment = dr["Treatment"].ToString();
                model.Medications = dr["Medications"].ToString();
                model.BloodGroup = dr["BloodGroup"].ToString();
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(MedicalRecordViewModel model)
        {
            string Query = "SPMedicalRecordsDML ";


            dataAccessLayer = new DataAccessLayer();

            SqlParameter[] parameters = new SqlParameter[]
            {
                new SqlParameter("@Action","update"),
                new SqlParameter("@RecordID",model.RecordID),
                new SqlParameter("@PatientID",model.PatientID),
                new SqlParameter("@DoctorID",model.DoctorID),
                new SqlParameter("@Diagnosis",model.Diagnosis),
                new SqlParameter("@Treatment",model.Treatment),
                new SqlParameter("@Medications",model.Medications),
                new SqlParameter("@BloodGroup",model.BloodGroup),
            };

            DataTable result= dataAccessLayer.ExecuteStoredProcedure(Query, parameters);

            return RedirectToAction("Index");

            return View();

        }

        public ActionResult Delete(int id)
        {
            string query = "SPMedicalRecordsDML";

            dataAccessLayer = new DataAccessLayer();

            SqlParameter[] sqlParameters = new SqlParameter[]
            {
                new SqlParameter("@Action","Delete"),
                new SqlParameter("@RecordID", id),
            };
            DataTable result = dataAccessLayer.ExecuteStoredProcedure(query, sqlParameters);

            if(result.Rows.Count>0 )
            {
               

            }
            return RedirectToAction("Index");

            return View();

        }


    }
}

PatientManagementSoftware/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <!-- Bootstrap Styles-->
    <link href="~/Content/assets/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link href="~/Content/assets/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- Custom Styles-->
    <link href="~/Content/assets/assets/css/custom-styles.css" rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

    <link href="~/Content/btn-css/btn.css"  rel="stylesheet"/>

    <link href="~/Content/LOGIN_ASSETS/css/style.css" rel="stylesheet" />

    <link href="~/Content/LOGIN_ASSETS/css/style.css.map" />
    <link href="~/Content/Invoice/style.css" />

    <link href="~/Content/About/heading.css" />
    <script src="~/Content/About/scrollar_jascript.js"></script>

    <link href="~/Content/About/StyleSheet1.css" rel="stylesheet" />
   <script src="~/Content/btn-css/JavaScript.js"></script>

    <link href="~/Content/LOGIN_ASSETS/css/animate.css" rel="stylesheet" />
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index","Dashboard")">LOTUS</a>
            </div>

            <ul class="nav navbar-top-links navbar-left">
            </ul>

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a  href="@Url.Action("About","Home")" aria-expanded="false">
                        <i class="fa fa-adn fa-lg" style="font-size:22px;"></i><span style="font-size:17px;">bout</span>
                    </a>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a href="@Url.Action("Logout","Login")" aria-expanded="false" style="font-size:17px;"><i class="fa fa-user fa-fw"></i>Logout</a>

                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
        </nav>
        <!--/. NAV TOP  -->
        <!--/. NAV SIDE BAR START  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">

                    <li>
                        <a href="@Url.Action("Index","Dashboard")" class="@((Request.Url.AbsolutePath==Url.Action("Index","Dashboard") ) ? "active-menu":"") "><i class="fa fa-dashboard fa-lg"></i> Dashboard</a>
                    </li>


                    <li>
                        <a href="@Url.Action("Index","Doctor")" class="@((Request.Url.AbsolutePath==Url.Action("Index","Doctor") ) ? "active-menu":"")
                           @((Request.Url.AbsolutePath==Url.Action("Register","Doctor") ) ? "active-menu":"")  
                            @((Request.Url.AbsolutePath==Url.Action("Edit","Doctor") ) ? "active-menu":"")  "><i class="fa fa-stethoscope fa-lg"></i>Doctor</a>
                    </li>

                    
                    <li>
                        <a href="@Url.Action("Index","Patient")" class="@((Request.Url.AbsolutePath==Url.Action("Index","Patient") ) ? "active-menu":"")   @((Request.Url.AbsolutePath==Url.Action("Register","Patient") ) ? "active-menu":"")
                     @((Request.Url.AbsolutePath==Url.Action("Edit","Patient") ) ? "active-menu":"")"><i class="fa fa-wheelchair fa-lg"></i>Patient</a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index","Appointment")" class="@((Request.Url.AbsolutePath==Url.Action("Index","Appointment") ) ? "active-menu":"")  @((Request.Url.AbsolutePath==Url.Action("BookAppointment","Appointment") ) ? "active-menu":"")
                     @((Request.Url.AbsolutePath==Url.Action("EditAppointment","Appointment") ) ? "active-menu":"")"><i class="fa fa-pencil-square-o fa-lg"></i>Appointment</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Invoicing")" class="@((Request.Url.AbsolutePath==Url.Action("Index","Invoicing") ) ? "active-menu":"")    @((Request.Url.AbsolutePath==Url.Action("Invoice","Invoicing") ) ? "active-menu":"")  
  @((Request.Url.AbsolutePath==Url.Action("Edit","Invoicing") ) ? "active-menu":"") "><i class="fa fa-file fa-lg"></i>Invoicing
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","MedicalRecords")" class="@((Request.Url.AbsolutePath==Url.Action("Index","MedicalRecords") ) ? "active-menu":"")    @((Request.Url.AbsolutePath==Url.Action("AddMedicalRecord","MedicalRecords") ) ? "active-menu":"")  
  @((Request.Url.AbsolutePath==Url.Action("Edit","MedicalRecords") ) ? "active-menu":"")    "><i class="	fa fa-book fa-lg"></i>Medical Record</a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- /. NAV SIDE END HERE  -->

        <div id="page-wrapper">     
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            LoTus MediCare<small> Cure With the best</small>
                        </h1>
                    </div>
                </div>
                @RenderBody()
                <!-- /. ROW  -->
                <div class="row">

                    <!-- /.col-lg-12 -->
                </div>
                <footer class="footer">

                    <p class="tex"> <span class="typing-2"></span>“Healing Begins Here: Lotus Healthcare—Your Own Path to Wellness”</p>
                    <!--<div class="address">
        <p>Lotus Healthcare and Recovery Center</p>
        <p>751 Central Park #212</p>
        <p>Roseville, CA 95678</p>
        </div>
        <div class="about-me">-->
                    <!-- Information about you -->
                    <!--<p>About Me: I'm passionate about web development!</p>
        </div>-->
                </footer>
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
    <!-- JS Scripts-->
    <!-- jQuery Js -->
    <script src="~/Content/assets/assets/js/jquery-1.10.2.js"></script>
    <!-- Bootstrap Js -->
    <script src="~/Content/assets/assets/js/bootstrap.min.js"></script>
    <!-- Metis Menu Js -->
    <script src="~/Content/assets/assets/js/jquery.metisMenu.js"></script>
    <!-- Custom Js -->
    <script src="~/Content/assets/assets/js/custom-scripts.js"></script>
</body>
</html>

PatientManagementSoftware/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title justify-content: center;>@ViewBag.Title - My Asp.Net Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body class="" style="background-image: url('/Content/assets/assets/img/photo1717162240.jpeg'); background-size: cover; background-repeat: no-repeat; ">
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Patient Management Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>